### ISSUE TITLE
collaboration

### ISSUE THREAD

**Issue by mane06** [navtrack/navtrack#4]
Hello, are there plans to join us as collaborators or some method to help us so that the process can be a little faster?

**Comment by andreisabau** [comment]
Hello, in the future I would welcome any contribution to the project but at this moment I don't think it's a good idea.
Things are rapidly changing since I'm still working on the foundation for the whole solution and at this moment I want focus on stabilising everything and having a first version released.

**Comment by mane06** [comment]
ok I understand, well it was made to order
